Milestone 4
El-Potato-Slayer/react-calculator pull request #3
Opened 2021-07-06 13:32 UTC by El-Potato-Slayer

- Created the `logic` folder
- Installed Big.js
- Created the `calculate.js` and `operate.js` files

2021-07-06 15:03 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hi @El-Potato-Slayer, you have really made a great effort in completing the other milestones and getting this far. However before this milestone is approved, there are a couple of changes you need to make in regards to the requirements. Check my comments below ⬇️ 

*Please apply the changes requested and request another code review. All the best 💪 *

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-06 15:03 UTC, Elbie-em commented on src/components/App.js
> +
Only import the calculate module. Calling the function with no arguments as you have done is not required in this milestone.

2021-07-06 15:03 UTC, Elbie-em commented on src/logic/calculate.js
> +export default function calculate(calcData, buttonName) {
There is no import of operate.js, kindly add this.

2021-07-06 15:03 UTC, Elbie-em commented on src/logic/calculate.js
> +
- [ ] The calcData should have three properties {total, next, operation}. 'next' is basically the next value typed in the calculator or the previous value from the total when attempting multiple operations.

2021-07-06 15:03 UTC, Elbie-em commented on src/logic/calculate.js
> +}
- [ ] Add the operation property to your cases in order for your to calculate function to produce proper results.

2021-07-06 15:03 UTC, Elbie-em commented on src/logic/calculate.js
> +
- [ ] You can destructure your calcData to make your code more readable.

2021-07-06 15:03 UTC, Elbie-em commented on src/logic/operate.js
> +  if (operation === '+') {
- [ ] both numberOne and numberTwo should be wrapped in big.js, here is how you could handle it.
const num1 = Big(numberOne)
const num2 = Big(numberTwo)

2021-07-06 15:03 UTC, Elbie-em commented on src/logic/operate.js
> +}
- [ ] operate should switch operation and use plus, minus, times, div and modifier(
turning the number into a percentage based number, `e.g. 81 % == .81`)

2021-07-07 16:19 UTC, rukundoeric commented
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 
  

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/),
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

2021-07-09 13:56 UTC, merged